# fly.toml app configuration file generated for syntaxvoice-api on 2025-10-17T17:38:41+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'syntaxvoice-api'
primary_region = 'sin'

[build]
  dockerfile = 'Dockerfile'

[env]
  PORT = '1234'

[http_service]
  internal_port = 1234
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[http_service.checks]]

  [[http_service.checks]]
    interval = '15s'
    timeout = '2s'
    method = 'GET'
    path = '/'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
